# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_feed.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'data_feed.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x61ta_feed.proto\"2\n\x06\x43onfig\x12\x12\n\nbatch_size\x18\x01 \x01(\x05\x12\x14\n\x0c\x64\x61taset_path\x18\x02 \x01(\t\"&\n\x06Sample\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\r\n\x05label\x18\x02 \x01(\x0c\x32/\n\x08\x44\x61taFeed\x12#\n\x0bget_samples\x12\x07.Config\x1a\x07.Sample\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_feed_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONFIG']._serialized_start=19
  _globals['_CONFIG']._serialized_end=69
  _globals['_SAMPLE']._serialized_start=71
  _globals['_SAMPLE']._serialized_end=109
  _globals['_DATAFEED']._serialized_start=111
  _globals['_DATAFEED']._serialized_end=158
# @@protoc_insertion_point(module_scope)
