FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

COPY train_server.py /app

CMD ["python", "train_server.py", "-a", "alexnet", "--gpu", "0", "--batch-size", "1"]